%TAG !rs! tag:yaml.org,2002:rust/object:
---

definitions:
  Trunk:
    type: object
    properties:
      main_branch: string
      work_branches:
        oneOf:
          - type: object
            properties:
              ticket_id:
                $ref: '#/definitions/TicketId'
          - type: object
            properties:
              pattern: string

  TicketId:
    type: object
    properties:
      tracker:
        type: string
        enum: [jira]
      api_url: string
      api_token: string

type: object

properties:
  version:
    oneOf:
      - number
      - string
  workflows:
    type: object
    properties:
      trunk:
        $ref: '#/definitions/Trunk'
required: [version]
